# Generated by Django 5.0.4 on 2024-05-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
            ],
            options={
                'db_table': 'egg_groups',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('category_id', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('fling_power', models.IntegerField(blank=True, null=True)),
                ('fling_effect_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('identifier', models.CharField(max_length=79)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('generation_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('power', models.SmallIntegerField(blank=True, null=True)),
                ('pp', models.SmallIntegerField(blank=True, null=True)),
                ('accuracy', models.SmallIntegerField(blank=True, null=True)),
                ('priority', models.SmallIntegerField()),
                ('target_id', models.IntegerField()),
                ('damage_class_id', models.IntegerField()),
                ('effect_id', models.IntegerField()),
                ('effect_chance', models.IntegerField(blank=True, null=True)),
                ('contest_type_id', models.IntegerField(blank=True, null=True)),
                ('contest_effect_id', models.IntegerField(blank=True, null=True)),
                ('super_contest_effect_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moves',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('species_id', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('base_experience', models.IntegerField()),
                ('order', models.IntegerField()),
                ('is_default', models.BooleanField()),
            ],
            options={
                'db_table': 'pokemons',
            },
        ),
        migrations.CreateModel(
            name='PokemonEggGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField()),
                ('egg_group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'pokemon_egg_groups',
            },
        ),
        migrations.CreateModel(
            name='PokemonFormGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_form_id', models.IntegerField()),
                ('generation_id', models.IntegerField()),
                ('game_index', models.IntegerField()),
            ],
            options={
                'db_table': 'pokemon_form_generations',
            },
        ),
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('version_group_id', models.IntegerField()),
                ('move_id', models.IntegerField()),
                ('pokemon_move_method_id', models.IntegerField()),
                ('level', models.IntegerField()),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pokemon_moves',
            },
        ),
        migrations.CreateModel(
            name='PokemonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('stat_id', models.IntegerField()),
                ('base_stat', models.IntegerField()),
                ('effort', models.IntegerField()),
            ],
            options={
                'db_table': 'pokemon_stats',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('slot', models.IntegerField()),
            ],
            options={
                'db_table': 'pokemon_types',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('damage_class_id', models.IntegerField(blank=True, null=True)),
                ('identifier', models.CharField(max_length=79)),
                ('is_battle_only', models.BooleanField()),
                ('game_index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stats',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('generation_id', models.IntegerField()),
                ('damage_class_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'types',
            },
        ),
    ]
